spring:
  data:
    mongodb:
      uri: mongodb://localhost/rock-scissors-paper
game:
  moves:
    - name: rock
      defeats: scissors
    - name: scissors
      defeats: paper
    - name: paper
      defeats: rock