server:
  port: 9000

school:
  messages:
    landing: Online Language School.
    userfirstentry: Our available languages are German and English.
    german: Willkommen
    english: Welcome
  school-users:
    - username: michael
      password: geheim
      authorities: ROLE_USER, ROLE_LANGUAGE_GERMAN
    - username: stacey
      password: secret
      authorities: ROLE_USER, ROLE_LANGUAGE_ENGLISH
    - username: admin
      password: admin
      authorities: ROLE_ADMIN
counter:
  amount: 100
  interval: 5000