spring:
  datasource:
    url: jdbc:mysql://localhost/the-great-gatsby?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
choice:
  invite: 1
  invitation: 2
  concludeparty: 3
  exit: 4